runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /leaf\.ico
  static_files: leaf.ico
  upload: leaf\.ico
- url: /styles
  static_dir: styles
- url: /media
  static_dir: media
- url: /scripts
  static_dir: scripts
- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
